### ISSUE TITLE
Selector performance ?

### ISSUE THREAD

**Issue by turkeryildirim** [tylerchilds/cutestrap#41]
I think you havent consider rendering performance in first place as this is introduced as a "one page" framework but i believe doing some tweaks wont hurt anyone.

Using `.grid > *`, really? How about `.grid > div, .grid > section, .grid > article` at least ? or better to use an identifier for columns ?

**Comment by tylerchilds** [comment]
Closing due to this being a non-issue.

http://www.telerik.com/blogs/css-tip-star-selector-not-that-bad

> In every case (including devices), the universal rule had no meaningful impact on page rendering time.
