### ISSUE TITLE
Use of implicit labels is considered bad accessibility

### ISSUE THREAD

**Issue by nattarnoff** [tylerchilds/cutestrap#5]
Recent accessibility standards recommend using explicit labels with form elements. in order to achieve this use the `for` attribute in the label pointing to the `id` of the field.

Wrapping the label around the input creates an implicit label, and while not wrong, has inconsistent performance among assistive technology, like screen readers.

Current Cutestrap form HTML is 

```
<label class="textfield">
      <input type="text">
      <span class="textfield__label">Your Name</span>
    </label>
```

I'm recommending modifying the suggested code to be:

```
<div class="textfield">
    <label for="name">  
      <span class="textfield__label">Your Name</span>
    </label>
    <input type="text" id="name">
</div>
```

**Comment by tylerchilds** [comment]
Huh, I didn't realize implicit was inconsistent on screen readers. When using explicit, is it still okay to have the label just around the form input. Would we be able to do this?

```
<div class="textfield">  
  <input type="text" id="name">
  <label for="name">  
    Your Name
  </label>
</div>
```

I'd still be able to achieve all the styling with this, improve accessibility, and simplify the required markup.

**Comment by nattarnoff** [comment]
Your sample doesn't have the label around the input, so I assume you mean this:

```
<div class="textfield"> 
<label for="name">
      <input type="text" id="name"> 
      Your Name   
    </label>
</div>
```
Which I'll need to test to see what the responses would be. Technically code says it's explicit, but it isn't a code structure I have seen, nor do I know how systems respond. Let me ask a few folks and test a few things.

**Comment by tylerchilds** [comment]
Sorry, by around, I meant near, not wrapping. My bad. My code example speaks more clearly to what I'm trying to convey.

**Comment by tylerchilds** [comment]
It's exactly what you have just with the label after the input and I dropped the class name.

**Comment by nattarnoff** [comment]
Ahh! Yes, that totally works. Using the `for` means the AT will pick up on it wherever it is in the code base.

**Comment by tylerchilds** [comment]
Perfect, great suggestion, I'll update the forms to use this new syntax

**Comment by tylerchilds** [comment]
Note to self: when implementing this, don't forget to update the disabled states.

**Comment by thisconnect** [comment]
Will you support both syntax or drop implicit label?

@nattarnoff is there any blog post about the inconsistent performance of implicit label?

**Comment by patrickhlauke** [comment]
@nattarnoff 
> Recent accessibility standards recommend using explicit labels with form elements

which ones? i've not experienced any issues with implicit labelling in VO, JAWS or NVDA. agree that both syntaxes should remain supported, as it often comes down to a matter of taste/preference when coding

**Comment by tylerchilds** [comment]
@thisconnect @patrickhlauke I'd support both syntaxes. I'm also toying with the idea of doing a semantic class name vs BEM, but not sold on that yet for a couple reasons.

```
<!-- explicit -->
<div class="textfield">  
  <input type="text" id="name">
  <label for="name">  
    Your Name
  </label>
</div>

<!-- implicit  w/ semantic class -->
<label class="textfield">  
  <input type="text" id="name">
  <span class="label>  
    Your Name
  </span>
</label>
```

**Comment by tylerchilds** [comment]
Closing, the implicit labels score 100% on lighthouse.

**Comment by patrickhlauke** [comment]
:+1: as said, i have not encountered any real-world problems with AT (and no accessibility standards say anything about them being bad)
